---
# tasks file for bvansomeren.freebsd-jail-template

- name: ensure download folder
  file: 
    path: "{{ freebsd_jails_template_download }}"
    state: directory

- name: ensure release downloaded
  get_url: 
    url: "{{ freebsd_downloadsite }}/{{ freebsd_jails_release }}/{{ item.file }}"
    dest: "{{ freebsd_jails_template_download }}/{{ item.file }}"
  with_items: "{{ freebsd_jails_default_install }}"

- name: ensure jails dataset
  zfs:
    name: "{{ freebsd_jails_dataset }}"
    mountpoint: "{{ freebsd_jails_location }}"
    state: present

- name: ensure templates dataset
  zfs:
    name: "{{ freebsd_jails_template_dataset }}"
    state: present

- name: check if template exists
  stat:
    path: "{{ freebsd_jails_template_mount }}/{{ freebsd_jails_base_template_name }}"
  register: template_ds_exists

- name: proceed if template does not exist or freebsd_jails_base_template_noupdate is false
  include: template.yml
  static: no
  when: not template_ds_exists.stat.exists or not freebsd_jails_base_template_noupdate
